name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  prod-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.5.0]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn run build
    
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          since_last_remote_commit: true
          separator: ","

      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: /home/ubuntu/nextapp

      - name: Start pm2 using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/nextapp/
            pm2 delete NextApp
            pm2 start yarn --name NextApp -- start
            pm2 save
     