name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  prod-build:
    runs-on: ubuntu-latest

    steps:
      - run: ls .
      - name: Run comparision script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ls .