name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  prod-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.5.0]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn run build
      # - name: rsync deployments
      #   uses: burnett01/rsync-deployments@5.2
      #   with:
      #     switches: -avzr --delete
      #     path: ./
      #     remote_path: /home/ubuntu/nextapp/
      #     remote_host: ${{ secrets.HOST_DNS }}
      #     remote_user: ${{ secrets.USERNAME }}
      #     remote_key: ${{ secrets.EC2_SSH_KEY }}
      
      - name: Start pm2 using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rsync -avr --delete ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/ubuntu/nextapp
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/nextapp/
            pm2 delete NextApp
            pm2 start yarn --name NextApp -- start
            pm2 save
     