name: Build and Deploy

on:
  push:
    # branches:
    #   - main
    #   - dev

jobs:
  building-pipeline:
    name: ${{ github.ref }} building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.5.0]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      # - run: |
      #     if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
      #       echo "${{secrets.DEV_ENV}}">.env
      #     elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
      #       echo "${{secrets.UAT_ENV}}">.env
      #     elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
      #       echo "${{secrets.PROD_ENV}}">.env
      #     fi
      - run: yarn run build

      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "HOST_DNS=${{ secrets.DEV_HOST_DNS }}" >> $GITHUB_ENV
            echo "HOST_USERNAME=${{ secrets.DEV_HOST_USERNAME }}" >> $GITHUB_ENV
            echo "HOST_PORT=${{ vars.DEV_PORT }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            echo "HOST_DNS=${{ secrets.UAT_HOST_DNS }}" >> $GITHUB_ENV
            echo "HOST_USERNAME=${{ secrets.UAT_HOST_USERNAME }}" >> $GITHUB_ENV
            echo "HOST_PORT=${{ vars.UAT_PORT }}" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "HOST_DNS=${{ secrets.PROD_HOST_DNS }}" >> $GITHUB_ENV
            echo "HOST_USERNAME=${{ secrets.PROD_HOST_USERNAME }}" >> $GITHUB_ENV
            echo "HOST_PORT=${{ vars.PROD_PORT }}" >> $GITHUB_ENV
          fi



      - name: rsync deployments
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --delete 
          path: ./
          remote_path: /home/ubuntu/nextapp/
          remote_host: ${{ env.HOST_DNS }} 
          remote_user: ${{ env.HOST_USERNAME }}
          remote_key: ${{ secrets.HOST_SSH_KEY }} 

      - name: Start pm2 using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST_DNS }}
          username: ${{ env.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/nextapp/
            pm2 delete NextApp
            pm2 start yarn --name NextApp -- start --port "${{ env.HOST_PORT }}"
            pm2 save
     