name: Build and Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  prod-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.5.0]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'

      # - name: Cache Yarn dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       ~/.cache/yarn
      #       node_modules
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # - run: yarn install
      # - run: yarn run build

      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            HOST_DNS="${{ secrets.DEV_HOST_DNS }}"   
            echo "HOST_DNS=${HOST_DNS} >> $GITHUB_ENV
            "HOST_USERNAME="${{ secrets.DEV_HOST_USERNAME }}"
            echo "HOST_USERNAME=${HOST_USERNAME}" >> $GITHUB_ENV
            HOST_SSH_KEY="${{ secrets.DEV_SSH_KEY }}"
            echo "HOST_SSH_KEY=${HOST_SSH_KEY}" >> $GITHUB_ENV
          fi

      - name: rsync deployments
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --delete 
          path: ./
          remote_path: /home/ubuntu/nextapp/
          remote_host: ${{ env.HOST_DNS }} 
          remote_user: ${{ env.HOST_USERNAME }}
          remote_key: ${{ env.HOST_SSH_KEY }} 

      # - name: Start pm2 using ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST_DNS }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     script: |
      #       export NVM_DIR=~/.nvm
      #       source ~/.nvm/nvm.sh
      #       cd /home/ubuntu/nextapp/
      #       pm2 delete NextApp
      #       pm2 start yarn --name NextApp -- start
      #       pm2 save
     