name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  prod-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.5.0]

    steps:
    # download all the files from main branch to git runner
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
          cache: 'npm'

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn run build
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./
          remote_path: /home/ubuntu/nextapp/
          remote_host: ${{ secrets.HOST_DNS }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.EC2_SSH_KEY }}
      # - run: ls -a
      # - run: rsync -avr -e "ssh -i <(echo '${{ secrets.EC2_SSH_KEY }}')" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/home/ubuntu/nextapp
        # ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/path/to/remote/root/
        # host: ${{ secrets.HOST_DNS }}
        # username: ${{ secrets.USERNAME }}
        # key: ${{ secrets.EC2_SSH_KEY }}