
name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout the files
       uses: actions/checkout@v4

     - name: Deploy to Server 1
       uses: easingthemes/ssh-deploy@main
       env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}

     - name: Cache Node modules
       uses: actions/cache@v2
       with:
         path: |
           ~/.npm
           ~/.cache
           ./home/node_modules
         key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
         
     - name: Executing remote ssh commands using ssh key
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST_DNS }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
           cd home
           export NVM_DIR=~/.nvm
           source ~/.nvm/nvm.sh
           npm --help
           yarn install
           yarn build
           pm2 restart yarn "NextApp" || : && pm2 start yarn -- start --name "NextApp"
           
    
      
